root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "tmp/server"
full_bin = "tmp/server"
delay = 1000
exclude_dir = ["tmp", "migrations"]
include_ext = ["go", "tpl", "tmpl", "html"]
stop_on_error = true

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
